name : Docker image scan
on:
  workflow_call:
    inputs:
        backend_image:
            type: string
            required: true
        
        frontend_image:
            type: string
            required: true
        
        tag:
          type: string
          required: false
          default: latest
    secrets:
      DOCKER_USERNAME:
        required: true

jobs:
  image-scan:
    runs-on: ubuntu-latest
    steps:
      - name : Backend image scan
        uses : aquasecurity/trivy-action@master
        with:
            image-ref: ${{ secrets.DOCKER_USERNAME }}/${{ inputs.backend_image }}:${{ inputs.tag }} 
            format: table
            exit-code : "1"
            severity: 'CRITICAL,HIGH'
    
      - name : Frontend image scan
        uses : aquasecurity/trivy-action@master
        with:
            image-ref: ${{ secrets.DOCKER_USERNAME }}/${{ inputs.frontend_image }}:${{ inputs.tag }}
            format : table
            exit-code : "1"
            severity: "CRITICAL,HIGH"